### PR TITLE
Fix LogisticRegression and ConvNet data loading

### PR DESCRIPTION
**Pull request by MechCoder**
Loading the LogisticRegression and ConvNets benchmarks breaks on master. This fixes it such that it no longer breaks.

### CODE REVIEW

**Comment by MechCoder** [comment]
ping @mfeurer ?

**Review by mfeurer — APPROVED** [review]

**Comment by mfeurer** [comment]
Would it help you if we merge the (working) development branch into master?

**Comment by MechCoder** [comment]
sure, thanks.

**Comment by MechCoder** [comment]
Do you know if https://github.com/automl/HPOlib2/issues/2 can be fixed. It would be nice to have reproducible benchmarks.

**Comment by KEggensperger** [comment]
Yes, we planned to fix that for a long time. We already decided for a solution, but it is not yet implemented ...

**Comment by MechCoder** [comment]
Great, is there a pull request anywhere? I plan to do it locally anyway so I just do not want to duplicate work

**Comment by MechCoder** [comment]
Closing as this has been fixed in the development branch.

**Pull request closed without merging**
